/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    services: Service;
    projects: Project;
    posts: Post;
    testimonials: Testimonial;
    media: Media;
    'form-submissions': FormSubmission;
    users: User;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Use "home" for the homepage
   */
  slug: string;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  layout?:
    | (
        | {
            /**
             * Small label above the headline, e.g. "CUSTOM TEAM APPAREL"
             */
            eyebrow?: string | null;
            /**
             * Use a line break for a two-line headline, e.g. "Your Brand.\nMade Better."
             */
            headline: string;
            subhead?: string | null;
            backgroundImage?: (number | null) | Media;
            /**
             * Optional smaller foreground image for the layered/split hero treatment
             */
            secondaryImage?: (number | null) | Media;
            cta?: {
              type?: ('internal' | 'custom') | null;
              label?: string | null;
              internal?:
                | ({
                    relationTo: 'pages';
                    value: number | Page;
                  } | null)
                | ({
                    relationTo: 'services';
                    value: number | Service;
                  } | null)
                | ({
                    relationTo: 'posts';
                    value: number | Post;
                  } | null)
                | ({
                    relationTo: 'projects';
                    value: number | Project;
                  } | null);
              url?: string | null;
              newTab?: boolean | null;
            };
            secondaryCta?: {
              type?: ('internal' | 'custom') | null;
              label?: string | null;
              internal?:
                | ({
                    relationTo: 'pages';
                    value: number | Page;
                  } | null)
                | ({
                    relationTo: 'services';
                    value: number | Service;
                  } | null)
                | ({
                    relationTo: 'posts';
                    value: number | Post;
                  } | null)
                | ({
                    relationTo: 'projects';
                    value: number | Project;
                  } | null);
              url?: string | null;
              newTab?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            heading?: string | null;
            logos?:
              | {
                  name: string;
                  logo: number | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'trustedBrands';
          }
        | {
            heading?: string | null;
            source?: ('featured' | 'manual') | null;
            projects?: (number | Project)[] | null;
            limit?: number | null;
            cta?: {
              type?: ('internal' | 'custom') | null;
              label?: string | null;
              internal?:
                | ({
                    relationTo: 'pages';
                    value: number | Page;
                  } | null)
                | ({
                    relationTo: 'services';
                    value: number | Service;
                  } | null)
                | ({
                    relationTo: 'posts';
                    value: number | Post;
                  } | null)
                | ({
                    relationTo: 'projects';
                    value: number | Project;
                  } | null);
              url?: string | null;
              newTab?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'portfolioGrid';
          }
        | {
            heading?: string | null;
            source?: ('collection' | 'manual') | null;
            services?: (number | Service)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'servicesGrid';
          }
        | {
            heading?: string | null;
            steps?:
              | {
                  title: string;
                  description?: string | null;
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            cta?: {
              type?: ('internal' | 'custom') | null;
              label?: string | null;
              internal?:
                | ({
                    relationTo: 'pages';
                    value: number | Page;
                  } | null)
                | ({
                    relationTo: 'services';
                    value: number | Service;
                  } | null)
                | ({
                    relationTo: 'posts';
                    value: number | Post;
                  } | null)
                | ({
                    relationTo: 'projects';
                    value: number | Project;
                  } | null);
              url?: string | null;
              newTab?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'processSteps';
          }
        | {
            kicker?: string | null;
            heading?: string | null;
            body?: string | null;
            capabilities?:
              | {
                  label: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Screenshot of an example branded store, shown in a browser/device frame
             */
            storeMockupImage?: (number | null) | Media;
            cta?: {
              type?: ('internal' | 'custom') | null;
              label?: string | null;
              internal?:
                | ({
                    relationTo: 'pages';
                    value: number | Page;
                  } | null)
                | ({
                    relationTo: 'services';
                    value: number | Service;
                  } | null)
                | ({
                    relationTo: 'posts';
                    value: number | Post;
                  } | null)
                | ({
                    relationTo: 'projects';
                    value: number | Project;
                  } | null);
              url?: string | null;
              newTab?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'companyStores';
          }
        | {
            heading?: string | null;
            body?: string | null;
            items?:
              | {
                  /**
                   * e.g. "Drinkware"
                   */
                  label: string;
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            cta?: {
              type?: ('internal' | 'custom') | null;
              label?: string | null;
              internal?:
                | ({
                    relationTo: 'pages';
                    value: number | Page;
                  } | null)
                | ({
                    relationTo: 'services';
                    value: number | Service;
                  } | null)
                | ({
                    relationTo: 'posts';
                    value: number | Post;
                  } | null)
                | ({
                    relationTo: 'projects';
                    value: number | Project;
                  } | null);
              url?: string | null;
              newTab?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'promoSpotlight';
          }
        | {
            heading?: string | null;
            items?: (number | Testimonial)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            /**
             * e.g. "The Story"
             */
            kicker?: string | null;
            heading: string;
            body?: string | null;
            image?: (number | null) | Media;
            /**
             * Optional looping background video
             */
            video?: (number | null) | Media;
            cta?: {
              type?: ('internal' | 'custom') | null;
              label?: string | null;
              internal?:
                | ({
                    relationTo: 'pages';
                    value: number | Page;
                  } | null)
                | ({
                    relationTo: 'services';
                    value: number | Service;
                  } | null)
                | ({
                    relationTo: 'posts';
                    value: number | Post;
                  } | null)
                | ({
                    relationTo: 'projects';
                    value: number | Project;
                  } | null);
              url?: string | null;
              newTab?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'storyStatement';
          }
        | {
            heading: string;
            subhead?: string | null;
            cta?: {
              type?: ('internal' | 'custom') | null;
              label?: string | null;
              internal?:
                | ({
                    relationTo: 'pages';
                    value: number | Page;
                  } | null)
                | ({
                    relationTo: 'services';
                    value: number | Service;
                  } | null)
                | ({
                    relationTo: 'posts';
                    value: number | Post;
                  } | null)
                | ({
                    relationTo: 'projects';
                    value: number | Project;
                  } | null);
              url?: string | null;
              newTab?: boolean | null;
            };
            style?: ('dark' | 'light' | 'accent') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBanner';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            width?: ('narrow' | 'full') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            heading?: string | null;
            subhead?: string | null;
            formType?: ('quote' | 'contact') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactForm';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  slug: string;
  order?: number | null;
  /**
   * Short line shown on grid cards
   */
  summary?: string | null;
  heroImage?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  publishedDate?: string | null;
  excerpt?: string | null;
  coverImage?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  clientName: string;
  slug: string;
  /**
   * Show on homepage Our Work grid
   */
  featured?: boolean | null;
  order?: number | null;
  /**
   * e.g. "Employee Kits", "Event Merchandise", "Embroidered Headwear"
   */
  projectType: string;
  industry?: string | null;
  servicesProvided?: (number | Service)[] | null;
  coverImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  overview?: string | null;
  challenge?: string | null;
  solution?: string | null;
  resultsBody?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  testimonial?: (number | null) | Testimonial;
  relatedProjects?: (number | Project)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  authorName: string;
  /**
   * e.g. "Head Coach, Peoria United"
   */
  authorTitle?: string | null;
  authorPhoto?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  formType: 'quote' | 'contact';
  name: string;
  email: string;
  phone?: string | null;
  /**
   * Team, school, or business name
   */
  organization?: string | null;
  message?: string | null;
  /**
   * Where to send them, e.g. existing WooCommerce shop link
   */
  shopUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles?: ('admin' | 'editor')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              subhead?: T;
              backgroundImage?: T;
              secondaryImage?: T;
              cta?:
                | T
                | {
                    type?: T;
                    label?: T;
                    internal?: T;
                    url?: T;
                    newTab?: T;
                  };
              secondaryCta?:
                | T
                | {
                    type?: T;
                    label?: T;
                    internal?: T;
                    url?: T;
                    newTab?: T;
                  };
              id?: T;
              blockName?: T;
            };
        trustedBrands?:
          | T
          | {
              heading?: T;
              logos?:
                | T
                | {
                    name?: T;
                    logo?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        portfolioGrid?:
          | T
          | {
              heading?: T;
              source?: T;
              projects?: T;
              limit?: T;
              cta?:
                | T
                | {
                    type?: T;
                    label?: T;
                    internal?: T;
                    url?: T;
                    newTab?: T;
                  };
              id?: T;
              blockName?: T;
            };
        servicesGrid?:
          | T
          | {
              heading?: T;
              source?: T;
              services?: T;
              id?: T;
              blockName?: T;
            };
        processSteps?:
          | T
          | {
              heading?: T;
              steps?:
                | T
                | {
                    title?: T;
                    description?: T;
                    image?: T;
                    id?: T;
                  };
              cta?:
                | T
                | {
                    type?: T;
                    label?: T;
                    internal?: T;
                    url?: T;
                    newTab?: T;
                  };
              id?: T;
              blockName?: T;
            };
        companyStores?:
          | T
          | {
              kicker?: T;
              heading?: T;
              body?: T;
              capabilities?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              storeMockupImage?: T;
              cta?:
                | T
                | {
                    type?: T;
                    label?: T;
                    internal?: T;
                    url?: T;
                    newTab?: T;
                  };
              id?: T;
              blockName?: T;
            };
        promoSpotlight?:
          | T
          | {
              heading?: T;
              body?: T;
              items?:
                | T
                | {
                    label?: T;
                    image?: T;
                    id?: T;
                  };
              cta?:
                | T
                | {
                    type?: T;
                    label?: T;
                    internal?: T;
                    url?: T;
                    newTab?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              heading?: T;
              items?: T;
              id?: T;
              blockName?: T;
            };
        storyStatement?:
          | T
          | {
              kicker?: T;
              heading?: T;
              body?: T;
              image?: T;
              video?: T;
              cta?:
                | T
                | {
                    type?: T;
                    label?: T;
                    internal?: T;
                    url?: T;
                    newTab?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaBanner?:
          | T
          | {
              heading?: T;
              subhead?: T;
              cta?:
                | T
                | {
                    type?: T;
                    label?: T;
                    internal?: T;
                    url?: T;
                    newTab?: T;
                  };
              style?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              width?: T;
              id?: T;
              blockName?: T;
            };
        contactForm?:
          | T
          | {
              heading?: T;
              subhead?: T;
              formType?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  order?: T;
  summary?: T;
  heroImage?: T;
  body?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  clientName?: T;
  slug?: T;
  featured?: T;
  order?: T;
  projectType?: T;
  industry?: T;
  servicesProvided?: T;
  coverImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  overview?: T;
  challenge?: T;
  solution?: T;
  resultsBody?: T;
  testimonial?: T;
  relatedProjects?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publishedDate?: T;
  excerpt?: T;
  coverImage?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  authorName?: T;
  authorTitle?: T;
  authorPhoto?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  formType?: T;
  name?: T;
  email?: T;
  phone?: T;
  organization?: T;
  message?: T;
  shopUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link?: {
          type?: ('internal' | 'custom') | null;
          label?: string | null;
          internal?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'services';
                value: number | Service;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'projects';
                value: number | Project;
              } | null);
          url?: string | null;
          newTab?: boolean | null;
        };
        /**
         * Renders sub-items as a wide multi-column panel with descriptions (used for Services).
         */
        megaMenu?: boolean | null;
        /**
         * Dropdown items, e.g. Services > Screen Printing, Headwear...
         */
        subItems?:
          | {
              link?: {
                type?: ('internal' | 'custom') | null;
                label?: string | null;
                internal?:
                  | ({
                      relationTo: 'pages';
                      value: number | Page;
                    } | null)
                  | ({
                      relationTo: 'services';
                      value: number | Service;
                    } | null)
                  | ({
                      relationTo: 'posts';
                      value: number | Post;
                    } | null)
                  | ({
                      relationTo: 'projects';
                      value: number | Project;
                    } | null);
                url?: string | null;
                newTab?: boolean | null;
              };
              /**
               * Only shown in mega menu style, e.g. "High-quality custom printing for teams and events."
               */
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  quoteCta?: {
    type?: ('internal' | 'custom') | null;
    label?: string | null;
    internal?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'services';
          value: number | Service;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'projects';
          value: number | Project;
        } | null);
    url?: string | null;
    newTab?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  tagline?: string | null;
  columns?:
    | {
        heading: string;
        links?:
          | {
              link?: {
                type?: ('internal' | 'custom') | null;
                label?: string | null;
                internal?:
                  | ({
                      relationTo: 'pages';
                      value: number | Page;
                    } | null)
                  | ({
                      relationTo: 'services';
                      value: number | Service;
                    } | null)
                  | ({
                      relationTo: 'posts';
                      value: number | Post;
                    } | null)
                  | ({
                      relationTo: 'projects';
                      value: number | Project;
                    } | null);
                url?: string | null;
                newTab?: boolean | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  social?:
    | {
        platform?: ('instagram' | 'facebook' | 'youtube' | 'x') | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  newsletterEnabled?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  phone?: string | null;
  hours?: string | null;
  email?: string | null;
  address?: string | null;
  /**
   * Existing WooCommerce shop the "Shop" / "Login" links point to
   */
  externalShopUrl: string;
  /**
   * Existing quote request form, if kept external
   */
  quoteRequestUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              label?: T;
              internal?: T;
              url?: T;
              newTab?: T;
            };
        megaMenu?: T;
        subItems?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    label?: T;
                    internal?: T;
                    url?: T;
                    newTab?: T;
                  };
              description?: T;
              id?: T;
            };
        id?: T;
      };
  quoteCta?:
    | T
    | {
        type?: T;
        label?: T;
        internal?: T;
        url?: T;
        newTab?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  tagline?: T;
  columns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    label?: T;
                    internal?: T;
                    url?: T;
                    newTab?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  newsletterEnabled?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  phone?: T;
  hours?: T;
  email?: T;
  address?: T;
  externalShopUrl?: T;
  quoteRequestUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}