// Auto-generated by `payload generate:importmap`. A placeholder is committed
// here so the project structure is complete; running that command locally
// (after `npm install`) will populate this with your real component map.
export const importMap = {}
